import numpy as np
import matplotlib.pyplot as mp
f1=int(input("enter 1st frequency="))
f2=int(input("enter 2nd frequency="))
fs=int(input("enter sampled frequency="))
n=int(input("no.of samples="))
x=np.arange(n)
x1=np.sin(2*np.pi*f1/fs*x)
mp.subplot(3,1,1)
mp.plot(x,x1)
mp.title('sine wave')
mp.xlabel('time')
mp.ylabel('amplitude')
x2=np.sin(2*np.pi*f2/fs*x)
mp.subplot(3,1,2)
mp.plot(x,x2)
mp.title('sin wave')
mp.xlabel('time')
mp.ylabel('amplitude')
y=x1+x2
mp.subplot(3,1,3)
mp.plot(x,y)
mp.title('resultent')
mp.xlabel('time')
mp.ylabel('amplitude')
mp.show( )